// ignore_for_file: constant_identifier_names

enum DataSource {
  SUCCESS,
  NO_CONTENT,
  BAD_REQUEST,
  FORBIDDEN,
  UNAUTHORISED,
  NOT_FOUND,
  SERVER_ERROR,
  CONNECT_TIMEOUT,
  CANCEL,
  RECEIVE_TIMEOUT,
  SEND_TIMEOUT,
  CACHE_READ_ERROR,
  CACHE_WRITE_ERROR,
  NO_INTERNET_CONNECTION,
  BAD_CERTIFICATE_ERROR,
  CONNECTION_ERROR,
  DEFAULT
}
